import * as dotenv from 'dotenv';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';
import { Builder } from 'flatbuffers';

// Generated FlatBuffers accessors — regenerated by `node build_scripts/build-core.js`
import { InitMessage, EntityInit, TileEntry } from './generated/simple-rpg.js';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);

import type { TemplatedApp, WebSocket } from 'uWebSockets.js';
const uWS: typeof import('uWebSockets.js') = require('uWebSockets.js');

const port = process.env.PORT ? parseInt(process.env.PORT, 10) : 3001;
const bindHost = process.env.BIND_HOST || '0.0.0.0';
const publicHost = process.env.HOST || bindHost;

// ─── Load C++ Physics Engine ───
let gamecore: any;
try {
  const gamecorePath = path.resolve(__dirname, '../..', 'build', 'Release', 'gamecore.node');
  gamecore = require(gamecorePath);
  console.log('✓ Loaded C++ physics engine (gamecore.node)');
} catch (e) {
  console.error('Failed to load gamecore.node addon:', e);
  process.exit(1);
}

const GAME_TICK_RATE = 1000 / 60;

const physics = new gamecore.GameWorld();
console.log('Initialized C++ GameWorld physics engine');

try {
  const registryPath = path.resolve(__dirname, '../../src/assets/tiles_registry.json');
  const registryData = JSON.parse(require('fs').readFileSync(registryPath, 'utf8'));
  physics.setTileRegistry(registryData);
  console.log('Loaded TileRegistry into C++ core with', registryData.length, 'tiles.');
} catch (e) {
  console.error('Failed to load tiles_registry.json for C++ core:', e);
}

physics.spawnTestChest();
console.log('Spawned test chest at (0,0).');

// ─── Wire Protocol Type Bytes ───
// Must match MSG constants in src/modules/map_module/protocol/StateParser.ts
const MSG_INIT = 0x10;

// ─── FlatBuffers Init Message Builder ────────────────────────────────────────
//
// FlatBuffers rule: nested objects (strings, sub-tables, vectors) must be
// built BEFORE their parent table starts. We build inside-out.

function buildInitMessage(
  playerId: number,
  entities: Array<{ id: number; x: number; y: number; type: string; focusedId: number }>,
  tileRegistry: Array<{ id: number; name: string }>
): Uint8Array {
  const builder = new Builder(4096);

  // --- build each EntityInit offset (strings first, then table) ---
  const entityOffsets = entities.map(e => {
    const typeStr = builder.createString(e.type);
    EntityInit.startEntityInit(builder);
    EntityInit.addId(builder, e.id);
    EntityInit.addX(builder, e.x);
    EntityInit.addY(builder, e.y);
    EntityInit.addEntityType(builder, typeStr);
    EntityInit.addFocusedId(builder, e.focusedId);
    return EntityInit.endEntityInit(builder);
  });
  const entitiesVec = InitMessage.createEntitiesVector(builder, entityOffsets);

  // --- build each TileEntry offset ---
  const tileOffsets = tileRegistry.map(t => {
    const nameStr = builder.createString(t.name);
    TileEntry.startTileEntry(builder);
    TileEntry.addId(builder, t.id);
    TileEntry.addName(builder, nameStr);
    return TileEntry.endTileEntry(builder);
  });
  const tilesVec = InitMessage.createTileRegistryVector(builder, tileOffsets);

  // --- root table ---
  InitMessage.startInitMessage(builder);
  InitMessage.addPlayerId(builder, playerId);
  InitMessage.addEntities(builder, entitiesVec);
  InitMessage.addTileRegistry(builder, tilesVec);
  const msgOffset = InitMessage.endInitMessage(builder);
  builder.finish(msgOffset);

  // Prefix with the message type byte so the client can route without parsing
  const fbBytes = builder.asUint8Array();
  const framed = new Uint8Array(1 + fbBytes.length);
  framed[0] = MSG_INIT;
  framed.set(fbBytes, 1);
  return framed;
}

// ─── Per-Socket UserData ───
interface SocketData {
  id: number;
}

const TILE_SIZE = 40;
const CHUNK_PIXEL_SIZE = 16 * TILE_SIZE;
const GAME_TOPIC = 'game';

function sendChunk(ws: WebSocket<SocketData>, cx: number, cy: number, cz: number) {
  try {
    const chunkBuffer: Buffer = physics.getChunk(cx, cy, cz);
    const chunkVisuals: Buffer = physics.getChunkVisuals(cx, cy, cz);
    if (!chunkBuffer || !chunkVisuals) return;

    const header = Buffer.alloc(13);
    header.writeUInt8(1, 0);
    header.writeInt32LE(cx, 1);
    header.writeInt32LE(cy, 5);
    header.writeInt32LE(cz, 9);

    const message = Buffer.concat([header, chunkBuffer, chunkVisuals]);
    ws.send(message, true); // isBinary = true
  } catch (e) {
    console.error(`Failed to send chunk ${cx},${cy},${cz}:`, e);
  }
}

// ─── uWebSockets.js App ───
const app: TemplatedApp = uWS.App();

app.ws<SocketData>('/*', {
  /* Settings */
  maxPayloadLength: 64 * 1024,
  maxBackpressure: 1024 * 1024,
  idleTimeout: 120,
  sendPingsAutomatically: true,
  compression: uWS.DISABLED, // Binary protocol — no need for WS compression

  /* ─── Connection Opened ─── */
  open: (ws) => {
    const initialX = Math.random() * 800;
    const initialY = Math.random() * 600;

    const numericId: number = physics.addPlayer(initialX, initialY);

    const userData = ws.getUserData();
    userData.id = numericId;
    ws.subscribe(GAME_TOPIC);

    console.log(`[+] Player connected: ${numericId}`);

    try {
      const { players: physicsPlayers } = physics.getState();

      const entityList: Array<{ id: number; x: number; y: number; type: string; focusedId: number }> = [];
      for (const [pid, data] of Object.entries(physicsPlayers) as [string, any][]) {
        entityList.push({
          id: parseInt(pid),
          x: data.x,
          y: data.y,
          type: data.type || 'player',
          focusedId: data.focusedId || 0,
        });
      }

      const tileReg = physics.getTileRegistry();
      const tileList: Array<{ id: number; name: string }> = Object.entries(tileReg).map(
        ([id, name]) => ({ id: parseInt(id), name: name as string })
      );

      const initBytes = buildInitMessage(numericId, entityList, tileList);
      ws.send(Buffer.from(initBytes.buffer, initBytes.byteOffset, initBytes.byteLength), true);
    } catch (e) {
      console.error(`Failed to send init to ${numericId}:`, e);
    }

    // Send surrounding chunks
    const centerCX = Math.floor(initialX / CHUNK_PIXEL_SIZE);
    const centerCY = Math.floor(initialY / CHUNK_PIXEL_SIZE);
    const centerCZ = 0;

    for (let dx = -1; dx <= 1; dx++) {
      for (let dy = -1; dy <= 1; dy++) {
        for (let dz = -1; dz <= 0; dz++) {
          sendChunk(ws, centerCX + dx, centerCY + dy, centerCZ + dz);
        }
      }
    }
  },

  /* ─── Message Received ─── */
  message: (ws, message, isBinary) => {
    const { id } = ws.getUserData();

    try {
      if (isBinary) {
        const buf = Buffer.from(message);

        if (buf.length > 0 && buf[0] <= 0x03) {
          const result = physics.processInput(id, buf);
          if (result && typeof result === 'string' && result.length > 0) {
            ws.send(result, false);
          }
          return;
        }
      }

      const decoder = new TextDecoder();
      const data = JSON.parse(decoder.decode(message));

      if (data.type === 'ping') {
        ws.send(JSON.stringify({ type: 'pong', timestamp: data.timestamp }), false);
      }
    } catch (e) {
      console.error('Failed to parse message:', e);
    }
  },

  /* ─── Connection Closed ─── */
  close: (ws) => {
    const { id } = ws.getUserData();
    console.log(`[-] Player disconnected: ${id}`);
    physics.removePlayer(id);
  },
});

// ─── Start Server ───
app.listen(bindHost, port, (listenSocket) => {
  if (listenSocket) {
    console.log(`✓ uWebSockets.js server running on ws://${publicHost}:${port}`);
  } else {
    console.error(`✗ Failed to listen on ${bindHost}:${port}`);
    process.exit(1);
  }
});

// ─── 60fps Game Loop ───
setInterval(() => {
  try {
    physics.tick();

    const binaryState: ArrayBuffer = physics.getBinaryState();
    if (binaryState && binaryState.byteLength > 0) {
      app.publish(GAME_TOPIC, Buffer.from(binaryState), true);
    }
  } catch (e) {
    console.error('Error in game loop:', e);
  }
}, GAME_TICK_RATE);
