import { isSnapshotBuffer, MSG } from '../protocol/StateParser';
import { encodeAttackInput, encodeBlockInput, encodeMovement, encodeTransferItem, resetInputSequence } from '../protocol/InputEncoder';
import { loadWasm } from '../../../services/wasm-loader';
import { ByteBuffer } from 'flatbuffers';
import { createFrontendLogger } from '../../../services/logger';

// Generated FlatBuffers accessors — regenerated by `node build_scripts/build-core.js`
import { InitMessage } from '../../../generated/simple-rpg/init-message.js';
import { InteractionResponse } from '../../../generated/simple-rpg/interaction-response.js';
import { mapInteractionResponseToLootUpdate } from '@/api/realtime/gameplay-flatbuffer-mappers';

let socket: WebSocket | null = null;
let renderPort: MessagePort | null = null;
let memberToken: string | null = null;
let shouldReconnect = true;
const DEFAULT_WS_PORT = 3001;
const INIT_FRAME_PREFIX_BYTES = 1;
const INTERACTION_FRAME_PREFIX_BYTES = 1;
const COMBAT_EVENT_HEADER_BYTES = 4;
const COMBAT_EVENT_ENTRY_BYTES = 28;
const BODY_STATE_MANIFEST_HEADER_BYTES = 4;
const BODY_STATE_MANIFEST_ENTRY_BYTES = 16;

const getHostname = () => {
  try {
    return self.location.hostname;
  } catch (e) {
    return 'localhost';
  }
};

const resolvedWsBaseUrl = import.meta.env.VITE_WS_URL || `ws://${getHostname()}:${DEFAULT_WS_PORT}`;
const _logger = createFrontendLogger('gameplay');

// ─── FlatBuffers Init Message Decoder ────────────────────────────────────────
// Converts the binary FlatBuffer into the same plain-object shape the rest of
// the codebase already knows (id, players Record, tileRegistry Record).

function decodeInitMessage(bytes: Uint8Array) {
  const bb = new ByteBuffer(bytes.slice(INIT_FRAME_PREFIX_BYTES)); // skip the 0x10 type prefix byte
  const msg = InitMessage.getRootAsInitMessage(bb);

  const players: Record<string, { x: number; y: number; type: string; focusedId: number }> = {};
  for (let i = 0; i < msg.entitiesLength(); i++) {
    const e = msg.entities(i)!;
    players[e.id().toString()] = {
      x: e.x(),
      y: e.y(),
      type: e.entityType() ?? 'player',
      focusedId: e.focusedId(),
    };
  }

  const tileRegistry: Record<number, string> = {};
  for (let i = 0; i < msg.tileRegistryLength(); i++) {
    const t = msg.tileRegistry(i)!;
    tileRegistry[t.id()] = t.name() ?? '';
  }

  return { type: 'init', id: msg.playerId(), players, tileRegistry };
}

function decodeInteractionMessage(bytes: Uint8Array) {
  const bb = new ByteBuffer(bytes.slice(INTERACTION_FRAME_PREFIX_BYTES)); // skip 0x11 prefix
  const msg = InteractionResponse.getRootAsInteractionResponse(bb);
  return mapInteractionResponseToLootUpdate(msg);
}

function decodeCombatEvents(bytes: Uint8Array) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const count = view.getUint16(1, true);
  const events = [];

  for (let i = 0; i < count; i++) {
    const offset = COMBAT_EVENT_HEADER_BYTES + (i * COMBAT_EVENT_ENTRY_BYTES);
    if (offset + COMBAT_EVENT_ENTRY_BYTES > bytes.byteLength) break;

    events.push({
      tick: view.getUint32(offset + 0, true),
      attackerId: view.getUint32(offset + 4, true).toString(),
      victimId: view.getUint32(offset + 8, true).toString(),
      damage: view.getInt32(offset + 12, true) / 65536,
      remainingHp: view.getInt32(offset + 16, true) / 65536,
      eventType: view.getUint8(offset + 20),
      partId: view.getUint8(offset + 21),
      routedPartId: view.getUint8(offset + 22),
      flags: view.getUint8(offset + 23),
      attackEpoch: view.getUint16(offset + 24, true),
      visualTrackId: view.getUint8(offset + 26),
    });
  }

  return { type: 'combat_events', events };
}

export interface BodyStateManifestEntry {
  entityId: number;
  bodyStateVersion: number;
  shieldState: number;
  functionalFlags: number;
  disabledParts: number;
  hiddenParts: number;
}

function decodeBodyStateManifest(bytes: Uint8Array) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const count = view.getUint16(1, true);
  const entries: BodyStateManifestEntry[] = [];

  for (let i = 0; i < count; i++) {
    const offset = BODY_STATE_MANIFEST_HEADER_BYTES + (i * BODY_STATE_MANIFEST_ENTRY_BYTES);
    if (offset + BODY_STATE_MANIFEST_ENTRY_BYTES > bytes.byteLength) break;

    entries.push({
      entityId: view.getUint32(offset + 0, true),
      bodyStateVersion: view.getUint16(offset + 4, true),
      shieldState: view.getUint8(offset + 6),
      functionalFlags: view.getUint8(offset + 7),
      disabledParts: view.getUint32(offset + 8, true),
      hiddenParts: view.getUint32(offset + 12, true),
    });
  }

  return { type: 'body_state_manifest', entries };
}

function connect() {
  if (!memberToken) {
    _logger.warn('skipping gameplay connect because member token is missing');
    return;
  }

  const separator = resolvedWsBaseUrl.includes('?') ? '&' : '?';
  const wsUrl = `${resolvedWsBaseUrl}${separator}mode=gameplay&memberToken=${encodeURIComponent(memberToken)}`;
  _logger.log('opening gameplay socket', { wsUrl, memberToken });
  socket = new WebSocket(wsUrl);
  socket.binaryType = 'arraybuffer';
  resetInputSequence();

  socket.onopen = () => {
    _logger.log('gameplay socket connected', { memberToken });
  };

  socket.onmessage = (event) => {
    if (event.data instanceof ArrayBuffer) {
      const bytes = new Uint8Array(event.data);
      const firstByte = bytes[0];

      if (isSnapshotBuffer(event.data)) {
        // 60Hz binary snapshot → transfer directly to RenderWorker (zero-copy)
        renderPort?.postMessage({ type: 'binary_state', buffer: event.data }, [event.data]);
        return;
      }

      if (firstByte === MSG.CHUNK) {
        // Chunk tile data → RenderWorker
        renderPort?.postMessage({ type: 'chunk', buffer: event.data }, [event.data]);
        return;
      }

      if (firstByte === MSG.INIT) {
        // FlatBuffers InitMessage → decode and forward to both workers
        const initData = decodeInitMessage(bytes);
        _logger.log('received gameplay init frame', {
          playerId: initData.id,
          entityCount: Object.keys(initData.players).length,
        });
        renderPort?.postMessage(initData);
        self.postMessage(initData);
        return;
      }

      if (firstByte === MSG.INTERACTION) {
        const interactionData = decodeInteractionMessage(bytes);
        self.postMessage(interactionData);
        return;
      }

      if (firstByte === MSG.COMBAT) {
        const combatEvents = decodeCombatEvents(bytes);
        renderPort?.postMessage(combatEvents);
        self.postMessage(combatEvents);
        return;
      }

      if (firstByte === MSG.BODY_STATE) {
        const manifest = decodeBodyStateManifest(bytes);
        renderPort?.postMessage(manifest);
        return;
      }

      return;
    }

    // JSON fallback for low-frequency text messages (ping/pong)
    const data = JSON.parse(event.data as string);
    if (data.type === 'pong') {
      self.postMessage(data);
      return;
    }

    if (
      data.type === 'interaction_options' ||
      data.type === 'open_loot' ||
      data.type === 'player_inventory' ||
      data.type === 'station_state' ||
      data.type === 'crafting_inventory' ||
      data.type === 'crafting_result' ||
      data.type === 'crafting_error' ||
      data.type === 'session_closed' ||
      data.type === 'world_layer_debug' ||
      data.type === 'world_layer_validation'
    ) {
      if (data.type === 'session_closed') {
        shouldReconnect = false;
        _logger.warn('received gameplay session_closed', { reason: data.reason ?? null });
      }
      self.postMessage(data);
      return;
    }
  };

  const pingInterval = setInterval(() => {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'ping', timestamp: Date.now() }));
    }
  }, 2000);

  socket.onclose = () => {
    _logger.warn('gameplay socket closed', { shouldReconnect, memberToken });
    clearInterval(pingInterval);
    if (shouldReconnect) {
      setTimeout(connect, 1000);
    }
  };

  socket.onerror = () => {
    _logger.error('gameplay socket error', { memberToken });
  };
}

self.onmessage = (event) => {
  if (event.data.type === 'initPort') {
    loadWasm().then(() => {
      renderPort = event.data.port;
      memberToken = String(event.data.memberToken || '');
      shouldReconnect = true;
      _logger.log('initializing gameplay worker port', { memberToken });
      connect();
    });
  } else if (event.data.type === 'move') {
    if (socket?.readyState === WebSocket.OPEN) {
      const buf = encodeMovement(event.data.dx, event.data.dy);
      socket.send(buf);
    }
  } else if (event.data.type === 'interact') {
    if (socket?.readyState === WebSocket.OPEN) {
      if (event.data.targetId != null) {
        socket.send(JSON.stringify({ type: 'interact_target', targetId: event.data.targetId }));
      } else {
        socket.send(JSON.stringify({ type: 'interact_target', targetId: 0 }));
      }
    }
  } else if (event.data.type === 'transfer_item') {
    if (socket?.readyState === WebSocket.OPEN) {
      const buf = encodeTransferItem(
        Number(event.data.targetId),
        Number(event.data.fromContainer),
        Number(event.data.toContainer),
        Number(event.data.itemIndex),
      );
      socket.send(buf);
    }
  } else if (event.data.type === 'request_player_inventory') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'request_player_inventory' }));
    }
  } else if (event.data.type === 'attack') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(encodeAttackInput(Number(event.data.direction)));
    }
  } else if (event.data.type === 'block') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(encodeBlockInput(Boolean(event.data.active), Number(event.data.direction)));
    }
  } else if (event.data.type === 'equip_item') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'equip_item', itemIndex: Number(event.data.itemIndex) }));
    }
  } else if (event.data.type === 'request_body_state') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'request_body_state',
        entityId: Number(event.data.entityId || 0),
      }));
    }
  } else if (event.data.type === 'drop_item') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'drop_item',
        itemIndex: Number(event.data.itemIndex),
        targetId: Number(event.data.targetId || 0),
      }));
    }
  } else if (event.data.type === 'mine_tile') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'mine_tile',
        tileX: Number(event.data.tileX),
        tileY: Number(event.data.tileY),
      }));
    }
  } else if (event.data.type === 'request_station_state') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'request_station_state', stationId: Number(event.data.stationId || 0) }));
    }
  } else if (event.data.type === 'request_crafting_inventory') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'request_crafting_inventory' }));
    }
  } else if (event.data.type === 'insert_station_item') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'insert_station_item',
        stationId: Number(event.data.stationId || 0),
        itemIndex: Number(event.data.itemIndex || 0),
        slotId: event.data.slotId ?? undefined,
      }));
    }
  } else if (event.data.type === 'remove_station_item') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'remove_station_item',
        stationId: Number(event.data.stationId || 0),
        slotId: event.data.slotId ?? undefined,
      }));
    }
  } else if (event.data.type === 'start_heating') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'start_heating', stationId: Number(event.data.stationId || 0) }));
    }
  } else if (event.data.type === 'collect_smelt_result') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'collect_smelt_result',
        stationId: Number(event.data.stationId || 0),
        slotId: event.data.slotId ?? undefined,
      }));
    }
  } else if (event.data.type === 'cast_workpiece') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'cast_workpiece',
        stationId: Number(event.data.stationId || 0),
        mold: Number(event.data.mold || 0),
        width: Number(event.data.width || 0),
        length: Number(event.data.length || 0),
        thicknessRaw: Number(event.data.thicknessRaw || 0),
      }));
    }
  } else if (event.data.type === 'bend_workpiece') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'bend_workpiece',
        stationId: Number(event.data.stationId || 0),
        zone: Number(event.data.zone || 0),
        displacement: Number(event.data.displacement || 0),
      }));
    }
  } else if (event.data.type === 'forge_workpiece') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'forge_workpiece',
        stationId: Number(event.data.stationId || 0),
        zone: Number(event.data.zone || 0),
        intensity: Number(event.data.intensity || 0),
      }));
    }
  } else if (event.data.type === 'chip_workpiece') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'chip_workpiece',
        stationId: Number(event.data.stationId || 0),
        startX: Number(event.data.startX || 0),
        startY: Number(event.data.startY || 0),
        width: Number(event.data.width || 0),
        height: Number(event.data.height || 0),
      }));
    }
  } else if (event.data.type === 'sharpen_workpiece') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'sharpen_workpiece',
        stationId: Number(event.data.stationId || 0),
        side: Number(event.data.side || 0),
        amount: Number(event.data.amount || 0),
      }));
    }
  } else if (event.data.type === 'join_workpieces') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'join_workpieces',
        stationId: Number(event.data.stationId || 0),
      }));
    }
  }
};
