import { isSnapshotBuffer, MSG } from '../protocol/StateParser';
import { encodeMovement, encodeInteract, resetInputSequence } from '../protocol/InputEncoder';
import { loadWasm } from '../../../services/wasm-loader';
import { ByteBuffer } from 'flatbuffers';

// Generated FlatBuffers accessors — regenerated by `node build_scripts/build-core.js`
import { InitMessage } from '../../../generated/simple-rpg/init-message.js';

let socket: WebSocket | null = null;
let renderPort: MessagePort | null = null;

const getHostname = () => {
  try {
    return self.location.hostname;
  } catch (e) {
    return 'localhost';
  }
};

const wsUrl = import.meta.env.VITE_WS_URL || `ws://${getHostname()}:3001`;

// ─── FlatBuffers Init Message Decoder ────────────────────────────────────────
// Converts the binary FlatBuffer into the same plain-object shape the rest of
// the codebase already knows (id, players Record, tileRegistry Record).

function decodeInitMessage(bytes: Uint8Array) {
  const bb = new ByteBuffer(bytes.slice(1)); // skip the 0x10 type prefix byte
  const msg = InitMessage.getRootAsInitMessage(bb);

  const players: Record<string, { x: number; y: number; type: string; focusedId: number }> = {};
  for (let i = 0; i < msg.entitiesLength(); i++) {
    const e = msg.entities(i)!;
    players[e.id().toString()] = {
      x: e.x(),
      y: e.y(),
      type: e.entityType() ?? 'player',
      focusedId: e.focusedId(),
    };
  }

  const tileRegistry: Record<number, string> = {};
  for (let i = 0; i < msg.tileRegistryLength(); i++) {
    const t = msg.tileRegistry(i)!;
    tileRegistry[t.id()] = t.name() ?? '';
  }

  return { type: 'init', id: msg.playerId(), players, tileRegistry };
}

function connect() {
  socket = new WebSocket(wsUrl);
  socket.binaryType = 'arraybuffer';
  resetInputSequence();

  socket.onmessage = (event) => {
    if (event.data instanceof ArrayBuffer) {
      const bytes = new Uint8Array(event.data);
      const firstByte = bytes[0];

      if (isSnapshotBuffer(event.data)) {
        // 60Hz binary snapshot → transfer directly to RenderWorker (zero-copy)
        renderPort?.postMessage({ type: 'binary_state', buffer: event.data }, [event.data]);
        return;
      }

      if (firstByte === MSG.CHUNK) {
        // Chunk tile data → RenderWorker
        renderPort?.postMessage({ type: 'chunk', buffer: event.data }, [event.data]);
        return;
      }

      if (firstByte === MSG.INIT) {
        // FlatBuffers InitMessage → decode and forward to both workers
        const initData = decodeInitMessage(bytes);
        renderPort?.postMessage(initData);
        self.postMessage(initData);
        return;
      }

      // future MSG.INTERACTION (0x11) goes here
      return;
    }

    // JSON fallback for low-frequency text messages (ping/pong)
    const data = JSON.parse(event.data as string);
    if (data.type === 'pong') {
      self.postMessage(data);
    }
  };

  const pingInterval = setInterval(() => {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'ping', timestamp: Date.now() }));
    }
  }, 2000);

  socket.onclose = () => {
    clearInterval(pingInterval);
    setTimeout(connect, 1000);
  };
}

self.onmessage = (event) => {
  if (event.data.type === 'initPort') {
    loadWasm().then(() => {
      renderPort = event.data.port;
      connect();
    });
  } else if (event.data.type === 'move') {
    if (socket?.readyState === WebSocket.OPEN) {
      const buf = encodeMovement(event.data.dx, event.data.dy);
      socket.send(buf);
    }
  } else if (event.data.type === 'interact') {
    if (socket?.readyState === WebSocket.OPEN) {
      const buf = encodeInteract();
      socket.send(buf);
    }
  } else if (event.data.type === 'transfer_item') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify(event.data));
    }
  }
};
