import { isSnapshotBuffer, MSG } from '../protocol/StateParser';
import { encodeAttackInput, encodeBlockInput, encodeMovement, encodeTransferItem, resetInputSequence } from '../protocol/InputEncoder';
import { loadWasm } from '../../../services/wasm-loader';
import { ByteBuffer } from 'flatbuffers';

// Generated FlatBuffers accessors — regenerated by `node build_scripts/build-core.js`
import { InitMessage } from '../../../generated/simple-rpg/init-message.js';
import { InteractionResponse } from '../../../generated/simple-rpg/interaction-response.js';
import { InventoryContents } from '../../../generated/simple-rpg/inventory-contents.js';
import type { InventoryItemView, InventoryMetaView } from '@/modules/ui_module/components/inventory_view';

let socket: WebSocket | null = null;
let renderPort: MessagePort | null = null;
const DEFAULT_WS_PORT = 3001;
const INIT_FRAME_PREFIX_BYTES = 1;
const INTERACTION_FRAME_PREFIX_BYTES = 1;
const COMBAT_EVENT_HEADER_BYTES = 4;
const COMBAT_EVENT_ENTRY_BYTES = 28;
const BODY_STATE_MANIFEST_HEADER_BYTES = 4;
const BODY_STATE_MANIFEST_ENTRY_BYTES = 16;

const getHostname = () => {
  try {
    return self.location.hostname;
  } catch (e) {
    return 'localhost';
  }
};

const resolvedWsUrl = import.meta.env.VITE_WS_URL || `ws://${getHostname()}:${DEFAULT_WS_PORT}`;

// ─── FlatBuffers Init Message Decoder ────────────────────────────────────────
// Converts the binary FlatBuffer into the same plain-object shape the rest of
// the codebase already knows (id, players Record, tileRegistry Record).

function decodeInitMessage(bytes: Uint8Array) {
  const bb = new ByteBuffer(bytes.slice(INIT_FRAME_PREFIX_BYTES)); // skip the 0x10 type prefix byte
  const msg = InitMessage.getRootAsInitMessage(bb);

  const players: Record<string, { x: number; y: number; type: string; focusedId: number }> = {};
  for (let i = 0; i < msg.entitiesLength(); i++) {
    const e = msg.entities(i)!;
    players[e.id().toString()] = {
      x: e.x(),
      y: e.y(),
      type: e.entityType() ?? 'player',
      focusedId: e.focusedId(),
    };
  }

  const tileRegistry: Record<number, string> = {};
  for (let i = 0; i < msg.tileRegistryLength(); i++) {
    const t = msg.tileRegistry(i)!;
    tileRegistry[t.id()] = t.name() ?? '';
  }

  return { type: 'init', id: msg.playerId(), players, tileRegistry };
}

function decodeInventory(inventory: InventoryContents | null, prefix: string): { items: InventoryItemView[]; meta: InventoryMetaView } {
  const items: InventoryItemView[] = [];

  if (inventory) {
    for (let i = 0; i < inventory.itemsLength(); i++) {
      const item = inventory.items(i);
      if (!item) continue;
      const weight = item.weight();
      const volume = item.volume();
      const quantity = item.quantity();
      items.push({
        id: `${prefix}-${i}-${item.name() ?? 'item'}`,
        name: item.name() ?? 'Unknown Item',
        spriteKey: item.spriteKey() ?? '',
        quantity,
        volume,
        weight,
        stackable: item.stackable(),
        maxStack: item.maxStack(),
        price: Math.max(1, Math.round((weight + volume) * 25)),
        equipped: false,
        equipSlot: '',
      });
    }
  }

  return {
    items,
    meta: {
      currentVolume: inventory?.currentVolume() ?? 0,
      maxVolume: inventory?.maxVolume() ?? 0,
      currentWeight: inventory?.currentWeight() ?? 0,
    },
  };
}

function decodeInteractionMessage(bytes: Uint8Array) {
  const bb = new ByteBuffer(bytes.slice(INTERACTION_FRAME_PREFIX_BYTES)); // skip 0x11 prefix
  const msg = InteractionResponse.getRootAsInteractionResponse(bb);

  const playerDecoded = decodeInventory(msg.playerInventory(), 'player');
  const targetDecoded = decodeInventory(msg.targetInventory(), `target-${msg.targetId()}`);

  return {
    type: 'open_loot',
    chestId: msg.targetId().toString(),
    interactionType: msg.interactionType() ?? 'loot',
    playerInventory: playerDecoded.items,
    chestInventory: targetDecoded.items,
    playerInventoryMeta: playerDecoded.meta,
    chestInventoryMeta: targetDecoded.meta,
  };
}

function decodeCombatEvents(bytes: Uint8Array) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const count = view.getUint16(1, true);
  const events = [];

  for (let i = 0; i < count; i++) {
    const offset = COMBAT_EVENT_HEADER_BYTES + (i * COMBAT_EVENT_ENTRY_BYTES);
    if (offset + COMBAT_EVENT_ENTRY_BYTES > bytes.byteLength) break;

    events.push({
      tick: view.getUint32(offset + 0, true),
      attackerId: view.getUint32(offset + 4, true).toString(),
      victimId: view.getUint32(offset + 8, true).toString(),
      damage: view.getInt32(offset + 12, true) / 65536,
      remainingHp: view.getInt32(offset + 16, true) / 65536,
      eventType: view.getUint8(offset + 20),
      partId: view.getUint8(offset + 21),
      routedPartId: view.getUint8(offset + 22),
      flags: view.getUint8(offset + 23),
      attackEpoch: view.getUint16(offset + 24, true),
      visualTrackId: view.getUint8(offset + 26),
    });
  }

  return { type: 'combat_events', events };
}

export interface BodyStateManifestEntry {
  entityId: number;
  bodyStateVersion: number;
  shieldState: number;
  functionalFlags: number;
  disabledParts: number;
  hiddenParts: number;
}

function decodeBodyStateManifest(bytes: Uint8Array) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const count = view.getUint16(1, true);
  const entries: BodyStateManifestEntry[] = [];

  for (let i = 0; i < count; i++) {
    const offset = BODY_STATE_MANIFEST_HEADER_BYTES + (i * BODY_STATE_MANIFEST_ENTRY_BYTES);
    if (offset + BODY_STATE_MANIFEST_ENTRY_BYTES > bytes.byteLength) break;

    entries.push({
      entityId: view.getUint32(offset + 0, true),
      bodyStateVersion: view.getUint16(offset + 4, true),
      shieldState: view.getUint8(offset + 6),
      functionalFlags: view.getUint8(offset + 7),
      disabledParts: view.getUint32(offset + 8, true),
      hiddenParts: view.getUint32(offset + 12, true),
    });
  }

  return { type: 'body_state_manifest', entries };
}

function connect() {
  socket = new WebSocket(resolvedWsUrl);
  socket.binaryType = 'arraybuffer';
  resetInputSequence();

  socket.onmessage = (event) => {
    if (event.data instanceof ArrayBuffer) {
      const bytes = new Uint8Array(event.data);
      const firstByte = bytes[0];

      if (isSnapshotBuffer(event.data)) {
        // 60Hz binary snapshot → transfer directly to RenderWorker (zero-copy)
        renderPort?.postMessage({ type: 'binary_state', buffer: event.data }, [event.data]);
        return;
      }

      if (firstByte === MSG.CHUNK) {
        // Chunk tile data → RenderWorker
        renderPort?.postMessage({ type: 'chunk', buffer: event.data }, [event.data]);
        return;
      }

      if (firstByte === MSG.INIT) {
        // FlatBuffers InitMessage → decode and forward to both workers
        const initData = decodeInitMessage(bytes);
        renderPort?.postMessage(initData);
        self.postMessage(initData);
        return;
      }

      if (firstByte === MSG.INTERACTION) {
        const interactionData = decodeInteractionMessage(bytes);
        self.postMessage(interactionData);
        return;
      }

      if (firstByte === MSG.COMBAT) {
        const combatEvents = decodeCombatEvents(bytes);
        renderPort?.postMessage(combatEvents);
        self.postMessage(combatEvents);
        return;
      }

      if (firstByte === MSG.BODY_STATE) {
        const manifest = decodeBodyStateManifest(bytes);
        renderPort?.postMessage(manifest);
        return;
      }

      return;
    }

    // JSON fallback for low-frequency text messages (ping/pong)
    const data = JSON.parse(event.data as string);
    if (data.type === 'pong') {
      self.postMessage(data);
      return;
    }

    if (
      data.type === 'interaction_options' ||
      data.type === 'open_loot' ||
      data.type === 'player_inventory' ||
      data.type === 'world_layer_debug' ||
      data.type === 'world_layer_validation'
    ) {
      self.postMessage(data);
      return;
    }
  };

  const pingInterval = setInterval(() => {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'ping', timestamp: Date.now() }));
    }
  }, 2000);

  socket.onclose = () => {
    clearInterval(pingInterval);
    setTimeout(connect, 1000);
  };
}

self.onmessage = (event) => {
  if (event.data.type === 'initPort') {
    loadWasm().then(() => {
      renderPort = event.data.port;
      connect();
    });
  } else if (event.data.type === 'move') {
    if (socket?.readyState === WebSocket.OPEN) {
      const buf = encodeMovement(event.data.dx, event.data.dy);
      socket.send(buf);
    }
  } else if (event.data.type === 'interact') {
    if (socket?.readyState === WebSocket.OPEN) {
      if (event.data.targetId != null) {
        socket.send(JSON.stringify({ type: 'interact_target', targetId: event.data.targetId }));
      } else {
        socket.send(JSON.stringify({ type: 'interact_target', targetId: 0 }));
      }
    }
  } else if (event.data.type === 'transfer_item') {
    if (socket?.readyState === WebSocket.OPEN) {
      const buf = encodeTransferItem(
        Number(event.data.targetId),
        Number(event.data.fromContainer),
        Number(event.data.toContainer),
        Number(event.data.itemIndex),
      );
      socket.send(buf);
    }
  } else if (event.data.type === 'request_player_inventory') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'request_player_inventory' }));
    }
  } else if (event.data.type === 'attack') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(encodeAttackInput(Number(event.data.direction)));
    }
  } else if (event.data.type === 'block') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(encodeBlockInput(Boolean(event.data.active), Number(event.data.direction)));
    }
  } else if (event.data.type === 'equip_item') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({ type: 'equip_item', itemIndex: Number(event.data.itemIndex) }));
    }
  } else if (event.data.type === 'request_body_state') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'request_body_state',
        entityId: Number(event.data.entityId || 0),
      }));
    }
  } else if (event.data.type === 'drop_item') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'drop_item',
        itemIndex: Number(event.data.itemIndex),
        targetId: Number(event.data.targetId || 0),
      }));
    }
  } else if (event.data.type === 'mine_tile') {
    if (socket?.readyState === WebSocket.OPEN) {
      socket.send(JSON.stringify({
        type: 'mine_tile',
        tileX: Number(event.data.tileX),
        tileY: Number(event.data.tileY),
      }));
    }
  }
};
